spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/expenses_tracker}
spring.datasource.username=${DB_USERNAME:springstudent}
spring.datasource.password=${DB_PASSWORD:springstudent}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.com.SpringBootMVC.ExpensesTracker=DEBUG
